package com.xuo.il2cppx.engine

import com.xuo.il2cppx.settings.DumpSettings
import java.io.BufferedWriter
import java.io.File

class DumpCsWriter(private val settings: DumpSettings? = null) {
    // Resolved type names: type array index → "Namespace.TypeName"
    private var resolvedTypeNames: Map<Int, String> = emptyMap()

    fun write(metadata: MetadataParseResult, outputFile: File, rvaResult: RvaResult? = null, elfInfo: ElfInfo? = null, libBytes: ByteArray? = null): Int {
        // Resolve Il2CppType array from ELF if available
        if (elfInfo != null && libBytes != null) {
            resolvedTypeNames = resolveIl2CppTypes(elfInfo, libBytes, metadata)
        }

        var typeWritten = 0
        outputFile.bufferedWriter().use { writer ->
            writer.line("// Generated by IL2CPP X Kotlin metadata dumper")
            writer.line("// Metadata version: ${metadata.version}")
            if (rvaResult != null) {
                writer.line("// RVA resolution: ${rvaResult.resolvedCount}/${rvaResult.totalMethods} methods (${(rvaResult.resolutionRate * 100).toInt()}%)")
            }
            if (resolvedTypeNames.isNotEmpty()) {
                writer.line("// Type resolution: ${resolvedTypeNames.size} types resolved from ELF")
            }
            writer.line()

            val images = metadata.images.filter { image ->
                image.typeStart >= 0 &&
                    image.typeCount >= 0 &&
                    image.typeStart + image.typeCount <= metadata.types.size
            }.takeIf { it.isNotEmpty() } ?: listOf(
                MetadataImage(index = 0, name = "global-metadata", typeStart = 0, typeCount = metadata.types.size)
            )
            val writtenTypeIndexes = HashSet<Int>()

            images.forEach { image ->
                writer.line("// Image ${image.index}: ${safeComment(image.name)}")
                val start = image.typeStart.coerceAtLeast(0)
                val end = (start + image.typeCount).coerceAtMost(metadata.types.size)
                if (start < end) {
                    for (typeIndex in start until end) {
                        if (!writtenTypeIndexes.add(typeIndex)) continue
                        val type = metadata.types[typeIndex]
                        if (type.name.isBlank()) continue
                        writer.writeType(metadata, type, rvaResult)
                        typeWritten++
                    }
                }
            }
        }
        return typeWritten
    }

    private fun BufferedWriter.writeType(metadata: MetadataParseResult, type: MetadataTypeDefinition, rvaResult: RvaResult? = null) {
        val namespaceName = sanitizeNamespace(type.namespaceName)
        if (namespaceName.isNotBlank()) {
            line("namespace $namespaceName")
            line("{")
        }

        val indent = if (namespaceName.isNotBlank()) "    " else ""
        line("${indent}// TypeDefIndex: ${type.index}")

        if (settings?.includeRvaInfo == true) {
            val image = metadata.images.firstOrNull { type.index in it.typeStart until it.typeStart + it.typeCount }
            if (image != null) {
                line("${indent}// Image: ${image.name}")
            }
        }

        val classDecl = buildString {
            append(indent)
            append("public class ")
            append(sanitizeIdentifier(type.name))

            if (settings?.includeInheritance == true) {
                // Show inheritance hint from image context
                val image = metadata.images.firstOrNull { type.index in it.typeStart until it.typeStart + it.typeCount }
                if (image != null) {
                    append(" // Assembly: ").append(sanitizeIdentifier(image.name))
                }
            }
        }
        line(classDecl)
        line("${indent}{")

        if (settings?.includeRvaInfo == true) {
            line("${indent}    // Fields: ${type.fieldCount}, Methods: ${type.methodCount}, Properties: ${type.propertyCount}")
            val typeRva = rvaResult?.typeRvas?.get(type.index)
            if (typeRva != null) {
                line("${indent}    // Resolved RVAs: ${typeRva.methods.size}/${type.methodCount}")
            }
            line()
        }

        writeFields(metadata, type, "$indent    ")
        writeMethods(metadata, type, "$indent    ", rvaResult)

        line("$indent}")
        if (namespaceName.isNotBlank()) {
            line("}")
        }
        line()
    }

    private fun BufferedWriter.writeFields(metadata: MetadataParseResult, type: MetadataTypeDefinition, indent: String) {
        val start = type.fieldStart
        if (start < 0 || type.fieldCount <= 0 || type.fieldCount > MAX_FIELDS_PER_TYPE || start >= metadata.fields.size) return
        val end = (start + type.fieldCount).coerceAtMost(metadata.fields.size)
        if (start >= end) return
        line("${indent}// Fields")
        for (fieldIndex in start until end) {
            val field = metadata.fields[fieldIndex]
            val fieldName = sanitizeIdentifier(field.name.ifBlank { "field_$fieldIndex" })
            val typeName = resolveTypeName(field.typeIndex)
            line("${indent}public $typeName $fieldName;")
        }
        line()
    }

    private fun BufferedWriter.writeMethods(metadata: MetadataParseResult, type: MetadataTypeDefinition, indent: String, rvaResult: RvaResult? = null) {
        val start = type.methodStart.coerceAtLeast(0)
        val end = (start + type.methodCount).coerceAtMost(metadata.methods.size)
        if (start >= end) return
        line("${indent}// Methods")
        for (methodIndex in start until end) {
            val method = metadata.methods[methodIndex]
            val methodName = sanitizeMethodName(method.name.ifBlank { "method_$methodIndex" })
            val parameters = buildParameterList(metadata, method)
            val returnTypeName = resolveTypeName(method.returnType)
            val rva = rvaResult?.methodRvas?.get(methodIndex)
            val rvaComment = if (rva != null) {
                " /* RVA: ${rva.hexRva}, Size: ${rva.hexSize} */"
            } else {
                ""
            }
            line("${indent}public $returnTypeName $methodName($parameters) { }$rvaComment")
        }
        line()
    }

    private fun BufferedWriter.line(value: String = "") {
        write(value)
        newLine()
    }

    private fun buildParameterList(metadata: MetadataParseResult, method: MetadataMethodDefinition): String {
        val start = method.parameterStart
        val count = method.parameterCount
        if (start < 0 || start >= metadata.parameters.size || count <= 0 || count > MAX_PARAMETERS_PER_METHOD) {
            return ""
        }
        val end = (start + count).coerceAtMost(metadata.parameters.size)
        if (start >= end) return ""
        return (start until end).joinToString(", ") { index ->
            val parameter = metadata.parameters[index]
            val name = sanitizeIdentifier(parameter.name.ifBlank { "param_$index" })
            val typeName = resolveTypeName(parameter.typeIndex)
            "$typeName $name"
        }
    }

    private fun resolveTypeName(typeIndex: Int): String {
        return resolvedTypeNames[typeIndex] ?: "T$typeIndex"
    }

    private fun sanitizeNamespace(value: String): String = value
        .split('.')
        .mapNotNull { part -> sanitizeIdentifier(part).takeIf { it.isNotBlank() } }
        .joinToString(".")

    private fun sanitizeMethodName(value: String): String = when (value) {
        ".ctor" -> "ctor"
        ".cctor" -> "cctor"
        else -> sanitizeIdentifier(value)
    }

    private fun sanitizeIdentifier(value: String): String {
        if (value.isBlank()) return "_"
        val builder = StringBuilder()
        value.forEachIndexed { index, char ->
            val valid = char == '_' || char.isLetterOrDigit()
            val output = if (valid) char else '_'
            if (index == 0 && output.isDigit()) builder.append('_')
            builder.append(output)
        }
        val result = builder.toString().trim('_')
        return if (result.isBlank() || result in CSHARP_KEYWORDS) "_${result.ifBlank { "item" }}" else result
    }

    private fun safeComment(value: String): String = value.replace("\n", " ").replace("\r", " ")

    /**
     * Resolve Il2CppType array from ELF binary.
     *
     * The types array in MetadataRegistration is Il2CppType** — an array of pointers.
     * Each pointer points to an Il2CppType struct:
     *   +0: union { void* dummy; int32_t klassIndex; Il2CppType* type; ... } data
     *   +4/8: bitfields { attrs:16, type:8, num_mods:5, byref:1, pinned:1, valuetype:1 }
     *
     * On LE, the type kind byte is at offset +2 of the bitfield word,
     * so struct offset = data_size + 2 (6 on 32-bit, 10 on 64-bit).
     */
    private fun resolveIl2CppTypes(elfInfo: ElfInfo, libBytes: ByteArray, metadata: MetadataParseResult): Map<Int, String> {
        val is64 = elfInfo.is64Bit
        val isLe = elfInfo.isLittleEndian
        val ptrSize = if (is64) 8 else 4
        val byteOrder = if (isLe) java.nio.ByteOrder.LITTLE_ENDIAN else java.nio.ByteOrder.BIG_ENDIAN
        // Type kind byte offset in Il2CppType struct
        val typeKindOffset = if (isLe) ptrSize + 2 else ptrSize + 1

        // Build TypeDef index → name map
        val tdNames = mutableMapOf<Int, String>()
        for (td in metadata.types) {
            if (td.name.isNotBlank()) {
                tdNames[td.index] = if (td.namespaceName.isEmpty()) td.name else "${td.namespaceName}.${td.name}"
            }
        }

        // Find g_MetadataRegistration symbol
        val metaRegSymbol = elfInfo.findSymbol("g_MetadataRegistration")
        val typesInfo: Pair<Long, Int> = if (metaRegSymbol != null) {
            findTypesInMetadataReg(libBytes, elfInfo, metaRegSymbol.value, metadata.types.size, is64, isLe, ptrSize, byteOrder)
                ?: return emptyMap()
        } else {
            findTypesByScan(libBytes, elfInfo, metadata.types.size, is64, isLe, ptrSize, byteOrder)
                ?: return emptyMap()
        }

        val (typesArrayVa, typesCount) = typesInfo
        val typesPtrArrayFoff = elfInfo.vaddrToFileOffset(typesArrayVa)?.toInt() ?: return emptyMap()

        val primitiveNames = mapOf(
            1 to "void", 2 to "bool", 3 to "char", 4 to "sbyte", 5 to "byte",
            6 to "short", 7 to "ushort", 8 to "int", 9 to "uint",
            10 to "long", 11 to "ulong", 12 to "float", 13 to "double",
            14 to "string", 15 to "object", 22 to "TypedReference",
            24 to "IntPtr", 25 to "UIntPtr"
        )

        val result = mutableMapOf<Int, String>()

        for (i in 0 until typesCount) {
            val ptrEntryOff = typesPtrArrayFoff + i * ptrSize
            if (ptrEntryOff + ptrSize > libBytes.size) break

            val typeStructVa = readPointer(libBytes, ptrEntryOff, ptrSize, is64, byteOrder)
            if (typeStructVa == 0L) continue

            val typeFoff = elfInfo.vaddrToFileOffset(typeStructVa)?.toInt() ?: continue
            if (typeFoff + ptrSize + 4 > libBytes.size) continue

            // Read type kind from bitfield
            val typeKind = (libBytes[typeFoff + typeKindOffset].toInt() and 0xFF)
            // Read data from union at offset +0
            val typeData = if (is64) {
                readU64(libBytes, typeFoff, byteOrder).toInt()
            } else {
                readU32(libBytes, typeFoff, byteOrder)
            }

            val name = when (typeKind) {
                // Primitives
                in 1..15, 22, 24, 25 -> primitiveNames[typeKind]
                // CLASS(0x10) / VALUETYPE(0x11) — data = TypeDefinitionIndex
                0x10, 0x11 -> tdNames[typeData]
                // PTR(0x12) — data = Il2CppType*
                0x12 -> {
                    val inner = resolveTypeFromPtr(libBytes, elfInfo, typeData.toLong(), typeKindOffset, tdNames, is64, isLe, ptrSize, byteOrder)
                    "$inner*"
                }
                // SZARRAY(0x14) — data = Il2CppType*
                0x14 -> {
                    val inner = resolveTypeFromPtr(libBytes, elfInfo, typeData.toLong(), typeKindOffset, tdNames, is64, isLe, ptrSize, byteOrder)
                    "$inner[]"
                }
                // ARRAY(0x15) — data = Il2CppArrayType*
                0x15 -> {
                    val inner = resolveTypeFromPtr(libBytes, elfInfo, typeData.toLong(), typeKindOffset, tdNames, is64, isLe, ptrSize, byteOrder)
                    "$inner[...]"
                }
                // GENERICINST(0x1C)
                0x1C -> "GENERICINST_$typeData"
                // VAR(0x13) / MVAR(0x1E)
                0x13 -> "!$typeData"
                0x1E -> "!!$typeData"
                else -> null
            }

            if (name != null) {
                result[i] = name
            }
        }

        return result
    }

    private fun resolveTypeFromPtr(
        libBytes: ByteArray, elfInfo: ElfInfo, typePtrVa: Long,
        typeKindOffset: Int, tdNames: Map<Int, String>,
        is64: Boolean, isLe: Boolean, ptrSize: Int, byteOrder: java.nio.ByteOrder
    ): String {
        if (typePtrVa == 0L) return "?"
        val foff = elfInfo.vaddrToFileOffset(typePtrVa)?.toInt() ?: return "T@0x${typePtrVa.toString(16)}"
        if (foff + ptrSize + 4 > libBytes.size) return "T@0x${typePtrVa.toString(16)}"

        val kind = (libBytes[foff + typeKindOffset].toInt() and 0xFF)
        val data = if (is64) readU64(libBytes, foff, byteOrder).toInt() else readU32(libBytes, foff, byteOrder)

        return when (kind) {
            1 -> "void"; 2 -> "bool"; 3 -> "char"; 4 -> "sbyte"; 5 -> "byte"
            6 -> "short"; 7 -> "ushort"; 8 -> "int"; 9 -> "uint"
            10 -> "long"; 11 -> "ulong"; 12 -> "float"; 13 -> "double"
            14 -> "string"; 15 -> "object"
            0x10, 0x11 -> tdNames[data] ?: "T$data"
            0x12 -> {
                val inner = resolveTypeFromPtr(libBytes, elfInfo, data.toLong(), typeKindOffset, tdNames, is64, isLe, ptrSize, byteOrder)
                "$inner*"
            }
            0x14 -> {
                val inner = resolveTypeFromPtr(libBytes, elfInfo, data.toLong(), typeKindOffset, tdNames, is64, isLe, ptrSize, byteOrder)
                "$inner[]"
            }
            else -> "T$data(kind=$kind)"
        }
    }

    private fun findTypesInMetadataReg(
        libBytes: ByteArray, elfInfo: ElfInfo, structVa: Long,
        expectedCount: Int, is64: Boolean, isLe: Boolean, ptrSize: Int, byteOrder: java.nio.ByteOrder
    ): Pair<Long, Int>? {
        val structFoff = elfInfo.vaddrToFileOffset(structVa)?.toInt() ?: return null
        val structSize = if (is64) 128 else 64
        val end = (structFoff + structSize).coerceAtMost(libBytes.size)

        var offset = structFoff
        while (offset + ptrSize * 2 <= end) {
            val count = if (is64) readU64(libBytes, offset, byteOrder).toInt() else readU32(libBytes, offset, byteOrder)
            val ptr = readPointer(libBytes, offset + ptrSize, ptrSize, is64, byteOrder)

            if (count in (expectedCount / 2)..(expectedCount * 2) && ptr > 0x10000 && elfInfo.vaddrToFileOffset(ptr) != null) {
                return Pair(ptr, count)
            }
            offset += ptrSize
        }
        return null
    }

    private fun findTypesByScan(
        libBytes: ByteArray, elfInfo: ElfInfo,
        expectedCount: Int, is64: Boolean, isLe: Boolean, ptrSize: Int, byteOrder: java.nio.ByteOrder
    ): Pair<Long, Int>? {
        val dataRelRo = elfInfo.sections.firstOrNull { it.name == ".data.rel.ro" } ?: return null
        val start = elfInfo.vaddrToFileOffset(dataRelRo.addr)?.toInt() ?: return null
        val end = (start + dataRelRo.size.toInt()).coerceAtMost(libBytes.size)

        var off = start
        while (off + ptrSize * 2 <= end) {
            val count = if (is64) readU64(libBytes, off, byteOrder).toInt() else readU32(libBytes, off, byteOrder)
            val ptr = readPointer(libBytes, off + ptrSize, ptrSize, is64, byteOrder)

            if (count in (expectedCount / 2)..(expectedCount * 2) && ptr > 0x10000 && elfInfo.vaddrToFileOffset(ptr) != null) {
                return Pair(ptr, count)
            }
            off += ptrSize
        }
        return null
    }

    private fun readPointer(bytes: ByteArray, offset: Int, ptrSize: Int, is64: Boolean, order: java.nio.ByteOrder): Long {
        return if (is64) readU64(bytes, offset, order) else readU32(bytes, offset, order).toLong() and 0xFFFFFFFFL
    }

    private fun readU32(bytes: ByteArray, offset: Int, order: java.nio.ByteOrder): Int {
        val b0 = bytes[offset].toInt() and 0xFF
        val b1 = bytes[offset + 1].toInt() and 0xFF
        val b2 = bytes[offset + 2].toInt() and 0xFF
        val b3 = bytes[offset + 3].toInt() and 0xFF
        return if (order == java.nio.ByteOrder.LITTLE_ENDIAN) {
            b0 or (b1 shl 8) or (b2 shl 16) or (b3 shl 24)
        } else {
            (b0 shl 24) or (b1 shl 16) or (b2 shl 8) or b3
        }
    }

    private fun readU64(bytes: ByteArray, offset: Int, order: java.nio.ByteOrder): Long {
        val lo = readU32(bytes, offset, order).toLong() and 0xFFFFFFFFL
        val hi = readU32(bytes, offset + 4, order).toLong() and 0xFFFFFFFFL
        return if (order == java.nio.ByteOrder.LITTLE_ENDIAN) lo or (hi shl 32) else (lo shl 32) or hi
    }

    private companion object {
        const val MAX_FIELDS_PER_TYPE = 1000
        const val MAX_PARAMETERS_PER_METHOD = 32

        val CSHARP_KEYWORDS = setOf(
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum",
            "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto",
            "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
            "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public",
            "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
            "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        )
    }
}
