package com.xuo.il2cppx.engine

import com.xuo.il2cppx.settings.DumpSettings
import java.io.BufferedWriter
import java.io.File

class DumpCsWriter(private val settings: DumpSettings? = null) {
    fun write(metadata: MetadataParseResult, outputFile: File, rvaResult: RvaResult? = null): Int {
        var typeWritten = 0
        outputFile.bufferedWriter().use { writer ->
            writer.line("// Generated by IL2CPP X Kotlin metadata dumper")
            writer.line("// Metadata version: ${metadata.version}")
            if (rvaResult != null) {
                writer.line("// RVA resolution: ${rvaResult.resolvedCount}/${rvaResult.totalMethods} methods (${(rvaResult.resolutionRate * 100).toInt()}%)")
            }
            writer.line()

            val images = metadata.images.filter { image ->
                image.typeStart >= 0 &&
                    image.typeCount >= 0 &&
                    image.typeStart + image.typeCount <= metadata.types.size
            }.takeIf { it.isNotEmpty() } ?: listOf(
                MetadataImage(index = 0, name = "global-metadata", typeStart = 0, typeCount = metadata.types.size)
            )
            val writtenTypeIndexes = HashSet<Int>()

            images.forEach { image ->
                writer.line("// Image ${image.index}: ${safeComment(image.name)}")
                val start = image.typeStart.coerceAtLeast(0)
                val end = (start + image.typeCount).coerceAtMost(metadata.types.size)
                if (start < end) {
                    for (typeIndex in start until end) {
                        if (!writtenTypeIndexes.add(typeIndex)) continue
                        val type = metadata.types[typeIndex]
                        if (type.name.isBlank()) continue
                        writer.writeType(metadata, type, rvaResult)
                        typeWritten++
                    }
                }
            }
        }
        return typeWritten
    }

    private fun BufferedWriter.writeType(metadata: MetadataParseResult, type: MetadataTypeDefinition, rvaResult: RvaResult? = null) {
        val namespaceName = sanitizeNamespace(type.namespaceName)
        if (namespaceName.isNotBlank()) {
            line("namespace $namespaceName")
            line("{")
        }

        val indent = if (namespaceName.isNotBlank()) "    " else ""
        line("${indent}// TypeDefIndex: ${type.index}")

        if (settings?.includeRvaInfo == true) {
            val image = metadata.images.firstOrNull { type.index in it.typeStart until it.typeStart + it.typeCount }
            if (image != null) {
                line("${indent}// Image: ${image.name}")
            }
        }

        val classDecl = buildString {
            append(indent)
            append("public class ")
            append(sanitizeIdentifier(type.name))

            if (settings?.includeInheritance == true) {
                // Show inheritance hint from image context
                val image = metadata.images.firstOrNull { type.index in it.typeStart until it.typeStart + it.typeCount }
                if (image != null) {
                    append(" // Assembly: ").append(sanitizeIdentifier(image.name))
                }
            }
        }
        line(classDecl)
        line("${indent}{")

        if (settings?.includeRvaInfo == true) {
            line("${indent}    // Fields: ${type.fieldCount}, Methods: ${type.methodCount}, Properties: ${type.propertyCount}")
            val typeRva = rvaResult?.typeRvas?.get(type.index)
            if (typeRva != null) {
                line("${indent}    // Resolved RVAs: ${typeRva.methods.size}/${type.methodCount}")
            }
            line()
        }

        writeFields(metadata, type, "$indent    ")
        writeMethods(metadata, type, "$indent    ", rvaResult)

        line("$indent}")
        if (namespaceName.isNotBlank()) {
            line("}")
        }
        line()
    }

    private fun BufferedWriter.writeFields(metadata: MetadataParseResult, type: MetadataTypeDefinition, indent: String) {
        val start = type.fieldStart
        if (start < 0 || type.fieldCount <= 0 || type.fieldCount > MAX_FIELDS_PER_TYPE || start >= metadata.fields.size) return
        val end = (start + type.fieldCount).coerceAtMost(metadata.fields.size)
        if (start >= end) return
        line("${indent}// Fields")
        for (fieldIndex in start until end) {
            val field = metadata.fields[fieldIndex]
            val fieldName = sanitizeIdentifier(field.name.ifBlank { "field_$fieldIndex" })
            line("${indent}public /* typeIndex=${field.typeIndex} */ object $fieldName;")
        }
        line()
    }

    private fun BufferedWriter.writeMethods(metadata: MetadataParseResult, type: MetadataTypeDefinition, indent: String, rvaResult: RvaResult? = null) {
        val start = type.methodStart.coerceAtLeast(0)
        val end = (start + type.methodCount).coerceAtMost(metadata.methods.size)
        if (start >= end) return
        line("${indent}// Methods")
        for (methodIndex in start until end) {
            val method = metadata.methods[methodIndex]
            val methodName = sanitizeMethodName(method.name.ifBlank { "method_$methodIndex" })
            val parameters = buildParameterList(metadata, method)
            val rva = rvaResult?.methodRvas?.get(methodIndex)
            val rvaComment = if (rva != null) {
                " /* RVA: ${rva.hexRva}, Size: ${rva.hexSize} */"
            } else {
                ""
            }
            line("${indent}public /* returnType=${method.returnType}$rvaComment */ object $methodName($parameters) { }")
        }
        line()
    }

    private fun BufferedWriter.line(value: String = "") {
        write(value)
        newLine()
    }

    private fun buildParameterList(metadata: MetadataParseResult, method: MetadataMethodDefinition): String {
        val start = method.parameterStart
        val count = method.parameterCount
        if (start < 0 || start >= metadata.parameters.size || count <= 0 || count > MAX_PARAMETERS_PER_METHOD) {
            return ""
        }
        val end = (start + count).coerceAtMost(metadata.parameters.size)
        if (start >= end) return ""
        return (start until end).joinToString(", ") { index ->
            val parameter = metadata.parameters[index]
            val name = sanitizeIdentifier(parameter.name.ifBlank { "param_$index" })
            "/* typeIndex=${parameter.typeIndex} */ object $name"
        }
    }

    private fun sanitizeNamespace(value: String): String = value
        .split('.')
        .mapNotNull { part -> sanitizeIdentifier(part).takeIf { it.isNotBlank() } }
        .joinToString(".")

    private fun sanitizeMethodName(value: String): String = when (value) {
        ".ctor" -> "ctor"
        ".cctor" -> "cctor"
        else -> sanitizeIdentifier(value)
    }

    private fun sanitizeIdentifier(value: String): String {
        if (value.isBlank()) return "_"
        val builder = StringBuilder()
        value.forEachIndexed { index, char ->
            val valid = char == '_' || char.isLetterOrDigit()
            val output = if (valid) char else '_'
            if (index == 0 && output.isDigit()) builder.append('_')
            builder.append(output)
        }
        val result = builder.toString().trim('_')
        return if (result.isBlank() || result in CSHARP_KEYWORDS) "_${result.ifBlank { "item" }}" else result
    }

    private fun safeComment(value: String): String = value.replace("\n", " ").replace("\r", " ")

    private companion object {
        const val MAX_FIELDS_PER_TYPE = 1000
        const val MAX_PARAMETERS_PER_METHOD = 32

        val CSHARP_KEYWORDS = setOf(
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum",
            "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto",
            "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
            "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public",
            "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
            "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        )
    }
}
