use std::io::{BufWriter, Write};

use crate::metadata_models::*;
use crate::rva_resolver::RvaResult;

pub struct DumpCsWriter {
    pub include_rva_info: bool,
    pub include_inheritance: bool,
}

impl DumpCsWriter {
    pub fn new() -> Self {
        Self {
            include_rva_info: true,
            include_inheritance: true,
        }
    }

    /// Build a lookup from type_index -> "Namespace.TypeName" for display.
    fn build_type_name_map(metadata: &MetadataParseResult) -> std::collections::HashMap<usize, String> {
        let mut map = std::collections::HashMap::new();
        for t in &metadata.types {
            let fqcn = if !t.namespace_name.is_empty() {
                format!("{}.{}", t.namespace_name, t.name)
            } else {
                t.name.clone()
            };
            map.insert(t.index, fqcn);
        }
        map
    }

    pub fn write(
        &self,
        metadata: &MetadataParseResult,
        output_path: &str,
        rva_result: &RvaResult,
    ) -> std::io::Result<usize> {
        let file = std::fs::File::create(output_path)?;
        let mut w = BufWriter::new(file);
        let type_names = Self::build_type_name_map(metadata);

        writeln!(w, "// Generated by IL2CPP X Rust metadata dumper")?;
        writeln!(w, "// Metadata version: {}", metadata.version)?;
        writeln!(
            w,
            "// RVA resolution: {}/{} methods ({}%)",
            rva_result.resolved_count(),
            rva_result.total_methods,
            (rva_result.resolution_rate() * 100.0) as u32
        )?;
        writeln!(w)?;

        let valid_images: Vec<&MetadataImage> = metadata
            .images
            .iter()
            .filter(|img| {
                img.type_count > 0
                    && img.type_start + img.type_count <= metadata.types.len()
            })
            .collect();

        let mut written: usize = 0;
        let mut seen = std::collections::HashSet::new();

        // Write types grouped by valid images
        for image in &valid_images {
            writeln!(w, "// Image {}: {}", image.index, safe_comment(&image.name))?;
            let start = image.type_start;
            let end = std::cmp::min(start + image.type_count, metadata.types.len());
            if start < end {
                for type_idx in start..end {
                    if !seen.insert(type_idx) {
                        continue;
                    }
                    let type_def = &metadata.types[type_idx];
                    if type_def.name.is_empty() {
                        continue;
                    }
                    self.write_type(&mut w, metadata, type_def, rva_result, &type_names)?;
                    written += 1;
                }
            }
        }

        // Write types not covered by any image
        let uncovered: Vec<usize> = (0..metadata.types.len())
            .filter(|i| !seen.contains(i))
            .collect();
        if !uncovered.is_empty() {
            writeln!(w, "// Uncovered types ({} not in any image)", uncovered.len())?;
            for type_idx in uncovered {
                let type_def = &metadata.types[type_idx];
                if type_def.name.is_empty() {
                    continue;
                }
                self.write_type(&mut w, metadata, type_def, rva_result, &type_names)?;
                written += 1;
            }
        }

        w.flush()?;
        Ok(written)
    }

    fn write_type(
        &self,
        w: &mut BufWriter<std::fs::File>,
        metadata: &MetadataParseResult,
        type_def: &MetadataTypeDefinition,
        rva_result: &RvaResult,
        type_names: &std::collections::HashMap<usize, String>,
    ) -> std::io::Result<()> {
        let namespace = sanitize_namespace(&type_def.namespace_name);
        let indent;
        if !namespace.is_empty() {
            writeln!(w, "namespace {}", namespace)?;
            writeln!(w, "{{")?;
            indent = "    ";
        } else {
            indent = "";
        }

        writeln!(w, "{}// TypeDefIndex: {}", indent, type_def.index)?;

        if self.include_rva_info {
            if let Some(image) = metadata
                .images
                .iter()
                .find(|img| type_def.index >= img.type_start && type_def.index < img.type_start + img.type_count)
            {
                writeln!(w, "{}// Image: {}", indent, image.name)?;
            }
        }

        writeln!(
            w,
            "{}public class {}",
            indent,
            sanitize_identifier(&type_def.name)
        )?;

        if self.include_inheritance {
            if let Some(image) = metadata
                .images
                .iter()
                .find(|img| type_def.index >= img.type_start && type_def.index < img.type_start + img.type_count)
            {
                writeln!(w, "{}    // Assembly: {}", indent, sanitize_identifier(&image.name))?;
            }
        }

        writeln!(w, "{}{{", indent)?;

        if self.include_rva_info {
            writeln!(
                w,
                "{}    // Fields: {}, Methods: {}, Properties: {}",
                indent, type_def.field_count, type_def.method_count, type_def.property_count
            )?;
            if let Some(type_rva) = rva_result.type_rvas.get(&type_def.index) {
                writeln!(
                    w,
                    "{}    // Resolved RVAs: {}/{}",
                    indent,
                    type_rva.methods.len(),
                    type_def.method_count
                )?;
            }
            writeln!(w)?;
        }

        // Fields
        self.write_fields(w, metadata, type_def, &format!("{}    ", indent), type_names)?;

        // Methods
        self.write_methods(w, metadata, type_def, &format!("{}    ", indent), rva_result, type_names)?;

        writeln!(w, "{}}}", indent)?;
        if !namespace.is_empty() {
            writeln!(w, "}}")?;
        }
        writeln!(w)?;
        Ok(())
    }

    fn write_fields(
        &self,
        w: &mut BufWriter<std::fs::File>,
        metadata: &MetadataParseResult,
        type_def: &MetadataTypeDefinition,
        indent: &str,
        type_names: &std::collections::HashMap<usize, String>,
    ) -> std::io::Result<()> {
        let start = type_def.field_start;
        if type_def.field_count == 0 || start >= metadata.fields.len() {
            return Ok(());
        }
        let end = std::cmp::min(start + type_def.field_count, metadata.fields.len());
        if start >= end {
            return Ok(());
        }

        writeln!(w, "{}// Fields", indent)?;
        for field_idx in start..end {
            let field = &metadata.fields[field_idx];
            let default_name = format!("field_{}", field_idx);
            let name = sanitize_identifier(if field.name.is_empty() {
                &default_name
            } else {
                &field.name
            });
            let type_name = resolve_type_name(field.type_index, type_names);
            writeln!(
                w,
                "{}public {} {};",
                indent, type_name, name
            )?;
        }
        writeln!(w)?;
        Ok(())
    }

    fn write_methods(
        &self,
        w: &mut BufWriter<std::fs::File>,
        metadata: &MetadataParseResult,
        type_def: &MetadataTypeDefinition,
        indent: &str,
        rva_result: &RvaResult,
        type_names: &std::collections::HashMap<usize, String>,
    ) -> std::io::Result<()> {
        let start = type_def.method_start;
        let end = std::cmp::min(start + type_def.method_count, metadata.methods.len());
        if start >= end {
            return Ok(());
        }

        writeln!(w, "{}// Methods", indent)?;
        for method_idx in start..end {
            let method = &metadata.methods[method_idx];
            let default_name = format!("method_{}", method_idx);
            let name = sanitize_method_name(if method.name.is_empty() {
                &default_name
            } else {
                &method.name
            });
            let params = build_parameter_list(metadata, method, type_names);
            let return_type = resolve_type_name(method.return_type, type_names);
            let rva_comment = if let Some(rva) = rva_result.method_rvas.get(&method_idx) {
                format!(" /* RVA: {}, Size: {} */", rva.hex_rva(), rva.hex_size())
            } else {
                String::new()
            };
            writeln!(
                w,
                "{}public {} {}({}) {{ }}{}",
                indent, return_type, name, params, rva_comment
            )?;
        }
        writeln!(w)?;
        Ok(())
    }
}

fn build_parameter_list(
    metadata: &MetadataParseResult,
    method: &MetadataMethodDefinition,
    type_names: &std::collections::HashMap<usize, String>,
) -> String {
    let start = method.parameter_start;
    let count = method.parameter_count;
    if count == 0 || start >= metadata.parameters.len() {
        return String::new();
    }
    let end = std::cmp::min(start + count, metadata.parameters.len());
    if start >= end {
        return String::new();
    }

    let parts: Vec<String> = (start..end)
        .map(|idx| {
            let param = &metadata.parameters[idx];
            let default_name = format!("param_{}", idx);
            let name = sanitize_identifier(if param.name.is_empty() {
                &default_name
            } else {
                &param.name
            });
            let type_name = resolve_type_name(param.type_index, type_names);
            format!("{} {}", type_name, name)
        })
        .collect();
    parts.join(", ")
}

fn sanitize_namespace(value: &str) -> String {
    value
        .split('.')
        .filter_map(|part| {
            let s = sanitize_identifier(part);
            if s.is_empty() {
                None
            } else {
                Some(s)
            }
        })
        .collect::<Vec<_>>()
        .join(".")
}

fn sanitize_method_name(value: &str) -> String {
    match value {
        ".ctor" => "ctor".to_string(),
        ".cctor" => "cctor".to_string(),
        _ => sanitize_identifier(value),
    }
}

fn sanitize_identifier(value: &str) -> String {
    if value.is_empty() {
        return "_".to_string();
    }
    let mut result = String::new();
    for (i, ch) in value.chars().enumerate() {
        let valid = ch == '_' || ch.is_alphanumeric();
        let output = if valid { ch } else { '_' };
        if i == 0 && output.is_ascii_digit() {
            result.push('_');
        }
        result.push(output);
    }
    let trimmed = result.trim_matches('_').to_string();
    if trimmed.is_empty() || CSHARP_KEYWORDS.iter().any(|&k| k == trimmed.as_str()) {
        format!("_{}", if trimmed.is_empty() { "item" } else { &trimmed })
    } else {
        trimmed
    }
}

fn resolve_type_name(
    type_index: usize,
    type_names: &std::collections::HashMap<usize, String>,
) -> String {
    if let Some(name) = type_names.get(&type_index) {
        return name.clone();
    }
    // Common IL2CPP type indices for primitives (approximate)
    match type_index {
        1 => "void".to_string(),
        2 => "bool".to_string(),
        3 => "char".to_string(),
        4 => "sbyte".to_string(),
        5 => "byte".to_string(),
        6 => "short".to_string(),
        7 => "ushort".to_string(),
        8 => "int".to_string(),
        9 => "uint".to_string(),
        10 => "long".to_string(),
        11 => "ulong".to_string(),
        12 => "float".to_string(),
        13 => "double".to_string(),
        14 => "string".to_string(),
        _ => format!("T{}", type_index),
    }
}

fn safe_comment(value: &str) -> String {
    value.replace('\n', " ").replace('\r', " ")
}

const CSHARP_KEYWORDS: &[&str] = &[
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
    "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
    "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
    "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
    "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
    "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
    "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
    "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
    "void", "volatile", "while",
];
